# Generated by Django 5.1.1 on 2025-02-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login_api',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=25)),
                ('password', models.IntegerField(verbose_name='max_value=8')),
            ],
        ),
    ]
